# Generated by Django 4.0.3 on 2022-04-20 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 8, 19, 43, 616352, tzinfo=utc)),
        ),
    ]
