# Generated by Django 4.0.3 on 2022-04-24 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posts_slug_alter_posts_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 19, 36, 19, 37641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
