# Generated by Django 4.0.3 on 2022-04-29 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_slug_posts_heading_alter_posts_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='heading',
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 10, 16, 50, 207039, tzinfo=utc)),
        ),
    ]
