# Generated by Django 4.0.3 on 2022-04-30 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_posts_image_posts_slug_alter_posts_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 14, 42, 16, 84151, tzinfo=utc)),
        ),
    ]
