# Generated by Django 4.0.3 on 2022-04-30 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_posts_content_alter_posts_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 14, 59, 31, 622644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='/profile_pics/default.jpeg', upload_to='profile_pics'),
        ),
    ]
