# Generated by Django 4.0.3 on 2022-05-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_posts_date_posted_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
