# Generated by Django 4.0.3 on 2022-05-12 12:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_posts_content_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=blog.models.path_and_rename),
        ),
    ]
